name: Automerge Dev to Main

on:
  pull_request:
    branches:
      - dev

jobs:
  merge:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Merge into main
        run: |
          git config --global user.email "abhishekkfl@gmail.com"
          git config --global user.name "whoami-anoint"
          git checkout main
          git merge --no-ff ${{ github.event.pull_request.head.ref }}
          git push origin main
