name: Merge PR from dev to main

on:
  pull_request:
    branches:
      - dev

jobs:
  merge:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the code
        uses: actions/checkout@v2

      - name: Merge PR from dev to main
        if: github.event_name == 'pull_request' && github.event.action == 'opened' && github.event.pull_request.base.ref == 'main' && github.event.pull_request.head.ref == 'dev'
        run: |
          git config --global user.email "github-actions@github.com"
          git config --global user.name "GitHub Actions"
          git fetch origin dev:dev
          git checkout main
          git merge --no-ff --no-edit dev
          git push origin main
