on:
  pull_request:
    branches:
      - dev

jobs:
  auto-merge:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Determine source branch of pull request
        id: determine_source_branch
        run: |
          SOURCE_BRANCH=$(jq -r '.pull_request.head.ref' "$GITHUB_EVENT_PATH")
          echo "Source branch of pull request: $SOURCE_BRANCH"
          echo "::set-output name=source_branch::$SOURCE_BRANCH"

      - name: Check if source branch is features
        run: |
          if [[ "${{ steps.determine_source_branch.outputs.source_branch }}" == "features" ]]; then
            echo "Pull request is from features branch"
            # Perform auto-merge to dev here
          else
            echo "Pull request is not from features branch, skipping auto-merge"
            exit 0
          fi
